//
//  GeneratedAppIcons.swift
//  Raul
//
//  Generated by Scripts/generate-icon-previews.sh from the .icon bundles in Moves/Icons.
//  Do not edit; your changes will be overwritten on the next build.
//

extension MovesAppIcon {
    /// Every alternate icon that ships with the app, in Moves/Icons order.
    static let generatedAlternateNames: [String] = [
        "BMW",
        "DC",
        "IBM",
        "M-stadt",
        "MUC",
        "Mac",
        "Magicalt",
        "Magicneu",
        "Moritz",
        "NYC",
        "OG",
        "Pride",
        "TLS2016",
        "TLSold",
        "barcelona",
        "berg",
        "doom",
        "impossible",
        "ironMaiden",
        "ironMaiden2",
        "ironman",
        "macro",
        "madsen",
        "magnum",
        "mario",
        "mars",
        "maserati",
        "massi",
        "mclaren",
        "megadrive",
        "megadrive2",
        "megaman",
        "megamanPerspective",
        "metallica",
        "metroMelbourne",
        "metroid",
        "milka",
        "mms",
        "monsterEnergy",
        "monsters",
        "montblanc",
        "mortal",
        "moto",
        "paris",
        "star",
        "sunshine",
        "sydney",
    ]
}
